export const FOCUS_PLANNED_SECONDS_MIN = 60;
export const FOCUS_PLANNED_SECONDS_MAX = 4 * 60 * 60;
export const FOCUS_BREAK_SECONDS_MIN = 60;
export const FOCUS_BREAK_SECONDS_MAX = 60 * 60;
export const FOCUS_PLANNED_SECONDS_STEP = 60;

export const FOCUS_RECORDED_SECONDS_MAX = 2_147_483_647;
export const FOCUS_CORRECTION_SECONDS_MAX = 7 * 24 * 60 * 60;

export const FOCUS_HISTORY_DEFAULT_ITEMS = 20;
export const FOCUS_HISTORY_MAX_ITEMS = 50;
export const FOCUS_SUMMARY_DAYS = 7;
export const FOCUS_VERSION_MAX = 2_147_483_647;
